name: deploy github pages
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: actions/setup-node@v3
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: yarn cache
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile && yarn build
      - name: upload dist
        uses: actions/upload-artifact@v3
        with:
          name: build-pages
          path: dist
          retention-days: 1

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: download build files
        uses: actions/download-artifact@v3
        with:
          name: build-pages
          path: dist
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: dist
